---
# tasks file for configure-tmux
- name: "Install vim"
  apt: 
    name: vim
    state: present
  become: true
  become_method: sudo
- name: "Download Latest dotfiles"
  git:
    repo: https://github.com/lowercasenumbers/dotfiles.git
    dest: "{{ ansible_env.HOME}}/code/dotfiles"
    clone: yes
    update: yes
    force: yes
- name: "Copy .vimrc file"
  copy:
    src: "{{ ansible_env.HOME }}/code/dotfiles/.vimrc"
    dest: "{{ ansible_env.HOME }}/.vimrc"
